package com.xuyazhou.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xuyazhou.bean.JsonData;
import com.xuyazhou.bean.UserBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig jsonDaoConfig;

    private final UserBeanDao userBeanDao;
    private final JsonDao jsonDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        jsonDaoConfig = daoConfigMap.get(JsonDao.class).clone();
        jsonDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        jsonDao = new JsonDao(jsonDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(JsonData.class, jsonDao);
    }
    
    public void clear() {
        userBeanDaoConfig.getIdentityScope().clear();
        jsonDaoConfig.getIdentityScope().clear();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public JsonDao getJsonDao() {
        return jsonDao;
    }

}
