package com.xuyazhou.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JSON.
 */
public class JsonData {

    private String data_type;
    private String data;
    private String createTime;

    public JsonData() {
    }

    public JsonData(String data_type) {
        this.data_type = data_type;
    }

    public JsonData(String data_type, String data, String createTime) {
        this.data_type = data_type;
        this.data = data;
        this.createTime = createTime;
    }

    public String getData_type() {
        return data_type;
    }

    public void setData_type(String data_type) {
        this.data_type = data_type;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
