package com.xuyazhou.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.xuyazhou.pagramx.bean.Counts;

/**
 * Entity mapped to table user.
 */
public class UserBean implements java.io.Serializable {

	private String index_id;
	private String id;
	private String username;
	private String bio;
	private String website;
	private String profile_picture;
	private String full_name;
	private String access_token;
	private String result;
	private Counts counts;

	public UserBean() {
	}

	public UserBean(String index_id) {
		this.index_id = index_id;
	}

	public UserBean(String index_id, String id, String username, String bio,
			String website, String profile_picture, String full_name,
			String access_token, String result) {
		this.index_id = index_id;
		this.id = id;
		this.username = username;
		this.bio = bio;
		this.website = website;
		this.profile_picture = profile_picture;
		this.full_name = full_name;
		this.access_token = access_token;
		this.result = result;
	}

	public Counts getCounts() {
		return counts;
	}

	public void setCounts(Counts counts) {
		this.counts = counts;
	}

	public String getIndex_id() {
		return index_id;
	}

	public void setIndex_id(String index_id) {
		this.index_id = index_id;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getBio() {
		return bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getProfile_picture() {
		return profile_picture;
	}

	public void setProfile_picture(String profile_picture) {
		this.profile_picture = profile_picture;
	}

	public String getFull_name() {
		return full_name;
	}

	public void setFull_name(String full_name) {
		this.full_name = full_name;
	}

	public String getAccess_token() {
		return access_token;
	}

	public void setAccess_token(String access_token) {
		this.access_token = access_token;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
